# quine_pack のうち、ボスの Quine のファイルを読んで確かめる部分（ADR 0009、tasks.md の T15c1）
#
# quine_pack.cmake から include() で読む。add_violation と read_checked_file は quine_pack.cmake のものを使う。
# Quine は1文字でもずれると自分を出力しなくなるので、マスクの形と1文字もずれていないことを確かめる。
#   - 改行は LF だけで、最後の行にも LF がある。CR、タブ、そのほかの制御文字、ASCII 以外の文字、NUL、BOM は違反
#   - 行の数と長さ（行末の空白を含む）がマスクと同じ
#   - . のマスは空白、$ のマスは $、# のマスは空白と $ のほかの表示できる ASCII（! から ~）

# マスクの1行を、Quine のファイルの1行に1文字ずつ合わせる正規表現にする（CMake の正規表現には {n} がないので、
# マスの数だけ並べる）
function(mask_row_regex row out_var)
    set(regex "^")
    string(LENGTH "${row}" row_len)
    set(column 0)
    while(column LESS row_len)
        string(SUBSTRING "${row}" ${column} 1 cell)
        if(cell STREQUAL "#")
            string(APPEND regex "[!-#%-~]")
        elseif(cell STREQUAL "$")
            string(APPEND regex "\\$")
        else()
            string(APPEND regex " ")
        endif()
        math(EXPR column "${column} + 1")
    endwhile()
    string(APPEND regex "$")
    set(${out_var} "${regex}" PARENT_SCOPE)
endfunction()

# 形が合わない行の、最初にずれたマスを違反にする（行の長さは同じとわかっている）
function(report_cell_mismatch rel row_no mask_row line)
    string(LENGTH "${mask_row}" row_len)
    set(column 0)
    while(column LESS row_len)
        string(SUBSTRING "${mask_row}" ${column} 1 cell)
        string(SUBSTRING "${line}" ${column} 1 c)
        math(EXPR column_no "${column} + 1")
        if(cell STREQUAL "." AND NOT c STREQUAL " ")
            add_violation("${rel}:${row_no}:${column_no}" ". のマスが空白でない（ADR 0009）" "")
            return()
        elseif(cell STREQUAL "$" AND NOT c STREQUAL "$")
            add_violation("${rel}:${row_no}:${column_no}" "$ のマスが $ でない（ADR 0009）" "")
            return()
        elseif(cell STREQUAL "#" AND (c STREQUAL " " OR c STREQUAL "$"))
            add_violation("${rel}:${row_no}:${column_no}" "# のマスが空白か $ になっている（# には、空白と $ のほかの表示できる ASCII を置く。ADR 0009）" "")
            return()
        endif()
        math(EXPR column "${column} + 1")
    endwhile()
endfunction()

# ボスの Quine のファイルを読んで確かめ、行をつなげたもの（columns*rows 文字）を QP_QUINE_<id>_TEXT に置く。
# mask_ok が FALSE（マスクがないか、マスクに違反がある）か、行の数がマスクと違うときは、文字の検査だけをして、
# 行ごとの形は比べない（原因と合わない違反を出さないため）。文字の違反がある行も、形を比べない。
# file(READ) は CRLF を LF に変えて読むので、文字の検査は HEX で読んだバイトで行う
function(check_quine_file path rel id mask_ok columns rows cells)
    read_checked_file("${path}" "${rel}" rest read_ok)
    if(NOT read_ok)
        return()
    endif()
    file(READ "${path}" hex HEX)
    if(hex MATCHES "^efbbbf")
        string(SUBSTRING "${hex}" 6 -1 hex)
    endif()
    # 1バイトごとに空白で区切り、LF（0a）で行に分ける（区切りのあとなので、0a はバイトの境目にだけ合う）
    string(REGEX REPLACE "(..)" "\\1 " hex_rest "${hex}")
    string(REPLACE "0a " "\n" hex_rest "${hex_rest}")
    string(REGEX REPLACE "[^\n]" "" newlines "${hex_rest}")
    string(LENGTH "${newlines}" line_count)
    set(missing_lf FALSE)
    if(NOT hex STREQUAL "" AND NOT hex MATCHES "0a$")
        set(missing_lf TRUE)
        math(EXPR line_count "${line_count} + 1")
    endif()
    set(compare_shape FALSE)
    if(mask_ok)
        if(line_count EQUAL rows)
            set(compare_shape TRUE)
        else()
            add_violation("${rel}" "行の数がマスクと違う（${line_count} 行。マスクは ${rows} 行。ADR 0009）" "")
        endif()
    endif()

    set(line_no 0)
    set(text "")
    while(line_no LESS line_count)
        string(FIND "${rest}" "\n" newline)
        string(FIND "${hex_rest}" "\n" hex_newline)
        if(newline EQUAL -1)
            set(line "${rest}")
            set(line_hex "${hex_rest}")
        else()
            string(SUBSTRING "${rest}" 0 ${newline} line)
            math(EXPR next "${newline} + 1")
            string(SUBSTRING "${rest}" ${next} -1 rest)
            string(SUBSTRING "${hex_rest}" 0 ${hex_newline} line_hex)
            math(EXPR next "${hex_newline} + 1")
            string(SUBSTRING "${hex_rest}" ${next} -1 hex_rest)
        endif()
        string(REPLACE " " "" line_hex "${line_hex}")
        math(EXPR line_no "${line_no} + 1")
        string(APPEND text "${line}")
        set(line_ok TRUE)
        if(line_hex MATCHES "^(..)*0d")
            add_violation("${rel}:${line_no}" "CR がある（改行は LF だけ。ADR 0009）" "")
            set(line_ok FALSE)
        endif()
        if(line_hex MATCHES "^(..)*09")
            add_violation("${rel}:${line_no}" "タブがある（ADR 0009）" "")
            set(line_ok FALSE)
        endif()
        if(line_hex MATCHES "^(..)*(0[0-8bcef]|1.|7f)")
            add_violation("${rel}:${line_no}" "制御文字がある（ADR 0009）" "")
            set(line_ok FALSE)
        endif()
        if(line_hex MATCHES "^(..)*[89a-f]")
            add_violation("${rel}:${line_no}" "ASCII 以外の文字がある（ADR 0009）" "")
            set(line_ok FALSE)
        endif()
        if(NOT line_ok OR NOT compare_shape)
            continue()
        endif()
        math(EXPR start "(${line_no} - 1) * ${columns}")
        string(SUBSTRING "${cells}" ${start} ${columns} mask_row)
        string(LENGTH "${line}" line_len)
        if(NOT line_len EQUAL columns)
            add_violation("${rel}:${line_no}" "行の長さがマスクと違う（${line_len} 文字。マスクは ${columns} 文字。行末の空白が消えていないか。ADR 0009）" "")
            continue()
        endif()
        mask_row_regex("${mask_row}" row_regex)
        if(NOT "${line}" MATCHES "${row_regex}")
            report_cell_mismatch("${rel}" ${line_no} "${mask_row}" "${line}")
        endif()
    endwhile()
    if(missing_lf)
        add_violation("${rel}:${line_no}" "最後の行に LF がない（ADR 0009）" "")
    endif()
    set_property(GLOBAL PROPERTY QP_QUINE_${id}_TEXT "${text}")
endfunction()

# QUINE_DIR の .cpp（サブディレクトリは見ない）を1つずつ確かめ、ボスの ID の一覧を out_var に返す。
# マスクの情報（mask_ids、mask_<id>_cells など）は、呼び出し側の quine_pack.cmake の変数を読む
function(read_quine_files out_var)
    file(GLOB quine_files LIST_DIRECTORIES false "${QUINE_DIR}/*.cpp")
    list(SORT quine_files)
    set(ids "")

    foreach(path IN LISTS quine_files)
        file(RELATIVE_PATH rel "${BASE_DIR}" "${path}")
        get_filename_component(id "${path}" NAME_WLE)
        if(NOT id MATCHES "^boss_")
            add_violation("${rel}" "Quine のファイルを使えるのはボス（boss_ で始まる ID の敵）だけ（雑魚は QUINE 範囲を使う。ADR 0009）" "")
            continue()
        elseif(NOT id MATCHES "${ID_REGEX}")
            add_violation("${rel}" "敵 ID に使えない文字がある（英小文字・数字・_ だけ。ADR 0002 のルール1）" "${id}")
            continue()
        endif()
        list(APPEND ids "${id}")
        # マスクに違反があるか（マスクの違反は、どれも「<マスク>:」で始まる。対応の違反は、まだ足していない）
        get_property(violations GLOBAL PROPERTY QP_VIOLATIONS)
        string(FIND "${violations}" "  ${mask_rel_dir}/${id}.txt:" mask_violation)
        if(id IN_LIST mask_ids AND mask_violation EQUAL -1)
            check_quine_file("${path}" "${rel}" "${id}" TRUE ${mask_${id}_columns} ${mask_${id}_rows} "${mask_${id}_cells}")
        else()
            check_quine_file("${path}" "${rel}" "${id}" FALSE 0 0 "")
        endif()
    endforeach()
    set(${out_var} "${ids}" PARENT_SCOPE)
endfunction()

# ボスのマスクと Quine のファイルの対応を確かめる。片方しかなければ違反にする
function(check_quine_correspondence mask_ids quine_ids)
    foreach(id IN LISTS mask_ids)
        if(id MATCHES "^boss_" AND NOT id IN_LIST quine_ids)
            add_violation("${mask_rel_dir}/${id}.txt" "Quine のファイルがない（${quine_rel_dir}/${id}.cpp。ADR 0009）" "")
        endif()
    endforeach()
    foreach(id IN LISTS quine_ids)
        if(NOT id IN_LIST mask_ids)
            add_violation("${quine_rel_dir}/${id}.cpp" "マスクがない（${mask_rel_dir}/${id}.txt）" "${id}")
        endif()
    endforeach()
endfunction()
