# quine_pack：QUINE 範囲を切り出して検査し、マスクに流し込んで、実行ファイルに埋め込む .cpp を生成する
# （ADR 0002、design.md §4、tasks.md の T15a）
#
# 使い方: cmake -DENEMY_DIR=<敵のソース> -DMASK_DIR=<マスク> -DOUTPUT=<生成する .cpp>
#               [-DBASE_DIR=<メッセージに出すパスの基準>] -P quine_pack.cmake
#
# ENEMY_DIR の .h と .cpp（サブディレクトリを含む）から QUINE 範囲を切り出し、MASK_DIR の <敵ID>.txt と対応させる。
# 違反があれば、ファイル名と行番号（マスクは行と列）と理由をすべて出して失敗し、OUTPUT は書かない。
# BASE_DIR を省くと、ENEMY_DIR の親を基準にする。
#
# CMake のリストは ; で割れるので、ソースとマスクの中身は list() や foreach() に渡さず、いつも引用符つきの変数で扱う。
# 違反は関数の入れ子の中からも足せるように、グローバルなプロパティに貯める。

cmake_minimum_required(VERSION 3.25)

foreach(arg ENEMY_DIR MASK_DIR OUTPUT)
    if(NOT DEFINED ${arg})
        message(FATAL_ERROR "${arg} を指定する")
    endif()
endforeach()
# パスの書き間違いで、敵が1体もないまま成功しないように、どちらのディレクトリもなければ止める
foreach(arg ENEMY_DIR MASK_DIR)
    if(NOT IS_DIRECTORY "${${arg}}")
        message(FATAL_ERROR "${arg} のディレクトリがない: ${${arg}}")
    endif()
endforeach()
if(NOT DEFINED BASE_DIR)
    get_filename_component(BASE_DIR "${ENEMY_DIR}" DIRECTORY)
endif()

# マスクの大きさの上限（ADR 0002 のルール6）
set(ZAKO_MAX_COLUMNS 24)
set(ZAKO_MAX_ROWS 10)
set(BOSS_MAX_COLUMNS 60)
set(BOSS_MAX_ROWS 24)
# QUINE 範囲に書いてよい大文字の名前（ADR 0002 のルール5）
set(ALLOWED_UPPER_NAMES PI DEG2RAD RAD2DEG)

set(ID_REGEX "^[a-z0-9_]+$")
# マーカーは、行の先頭（前の空白は除く）の // QUINE-BEGIN と // QUINE-END だけ（ADR 0002 のルール1）
set(MARKER_REGEX "^[ \t]*//[ \t]*QUINE-(BEGIN|END)([^A-Za-z0-9_-]|$)")
# C++ の pp-number（' は含めない。' は文字のリテラルと同じく違反にする）
set(NUMBER_REGEX "^\\.?[0-9]([eEpP][-+]|[0-9A-Za-z_.])*")

set_property(GLOBAL PROPERTY QP_VIOLATIONS "")
set_property(GLOBAL PROPERTY QP_VIOLATION_COUNT 0)

# where は「ファイル:行」か「ファイル:行:列」か「ファイル」。行の先頭に空白を置く（CMake がメッセージを折り返さないように）
function(add_violation where kind text)
    set(entry "  ${where}: ${kind}")
    if(NOT "${text}" STREQUAL "")
        string(APPEND entry ": ${text}")
    endif()
    set_property(GLOBAL APPEND_STRING PROPERTY QP_VIOLATIONS "${entry}\n")
    get_property(count GLOBAL PROPERTY QP_VIOLATION_COUNT)
    math(EXPR count "${count} + 1")
    set_property(GLOBAL PROPERTY QP_VIOLATION_COUNT ${count})
endfunction()

# ソースかマスクを読む。読めたら ok_var を TRUE にし、中身を out_var に返す。
# NUL があれば、違反にして ok_var を FALSE にする（file(READ) は NUL で中身を打ち切るので、そのファイルは検査できない。
# 読めなかった範囲のせいで、原因と合わない違反が出ないように、範囲とマスクの対応の検査も飛ばす）。
# 先頭の UTF-8 の BOM は違反にして、取り除いた中身を返す（1行目のマーカーやマスクの行を、BOM のせいで別の違反として
# 報告しないため）
function(read_checked_file path rel out_var ok_var)
    file(READ "${path}" hex HEX)
    # 2文字ずつ区切って、NUL（00）をバイトの境目でだけ探す
    string(REGEX REPLACE "(..)" "\\1 " spaced "${hex}")
    string(FIND "${spaced}" "00 " nul)
    if(NOT nul EQUAL -1)
        string(SUBSTRING "${spaced}" 0 ${nul} before)
        string(REGEX MATCHALL "0a " newlines "${before}")
        list(LENGTH newlines nul_line)
        math(EXPR nul_line "${nul_line} + 1")
        add_violation("${rel}:${nul_line}" "NUL 文字がある（ここで読み込みが止まるので、このファイルの検査と、範囲とマスクの対応の検査をしない）" "")
        set_property(GLOBAL PROPERTY QP_HAS_NUL TRUE)
        set(${ok_var} FALSE PARENT_SCOPE)
        return()
    endif()
    file(READ "${path}" content)
    if(hex MATCHES "^efbbbf")
        add_violation("${rel}:1" "ファイルの先頭に BOM がある（BOM なしの UTF-8 で保存する）" "")
        string(SUBSTRING "${content}" 3 -1 content)
    endif()
    set(${out_var} "${content}" PARENT_SCOPE)
    set(${ok_var} TRUE PARENT_SCOPE)
endfunction()

# 数値リテラル（pp-number）が、値が 0、1、2、0.5 の10進数か。小数部の桁数は問わない。
# 整数部の先頭の余分な 0、大文字の F、指数、ほかの接尾辞は認めない
function(is_allowed_number number out_var)
    set(ok FALSE)
    if("${number}" MATCHES "^(0|[1-9][0-9]*)?(\\.([0-9]*))?f?$")
        set(int_part "${CMAKE_MATCH_1}")
        set(frac_part "${CMAKE_MATCH_3}")
        string(REGEX REPLACE "0+$" "" frac_part "${frac_part}")
        if(int_part STREQUAL "")
            set(int_part 0)
        endif()
        if(int_part MATCHES "^[012]$" AND frac_part STREQUAL "")
            set(ok TRUE)
        elseif(int_part STREQUAL "0" AND frac_part STREQUAL "5")
            set(ok TRUE)
        endif()
    endif()
    set(${out_var} ${ok} PARENT_SCOPE)
endfunction()

# QUINE 範囲の中身を字句に分けて、コメント、" と ' と \、数値、大文字の名前を検査する。
# \ を止めるのは、行末の \ による行の連結で、数値やコメントを2行に分けて検査を抜けられないようにするため
# first_line は中身の1行目の行番号。ASCII 以外の文字は、切り出すときに行ごとに検査している
function(check_range_text rel first_line text)
    set(rest "${text}")
    set(line ${first_line})
    while(NOT "${rest}" STREQUAL "")
        if("${rest}" MATCHES "^[ \t\r\n]+")
            set(token "${CMAKE_MATCH_0}")
        elseif("${rest}" MATCHES "^//[^\n]*")
            set(token "${CMAKE_MATCH_0}")
            add_violation("${rel}:${line}" "コメントを書かない（ADR 0002 のルール7）" "${token}")
        elseif("${rest}" MATCHES "^/\\*")
            # 閉じの */ は、開きの /* のあとから探す（/*/ を閉じたコメントと取り違えないため）
            string(SUBSTRING "${rest}" 2 -1 body)
            string(FIND "${body}" "*/" close)
            if(close EQUAL -1)
                set(token "${rest}")
            else()
                math(EXPR token_len "${close} + 4")
                string(SUBSTRING "${rest}" 0 ${token_len} token)
            endif()
            string(REGEX MATCH "^[^\n]*" first_part "${token}")
            add_violation("${rel}:${line}" "コメントを書かない（ADR 0002 のルール7）" "${first_part}")
        elseif("${rest}" MATCHES "^[\"']")
            set(token "${CMAKE_MATCH_0}")
            add_violation("${rel}:${line}" "文字列と文字のリテラル（\" と '）を書かない（ADR 0002 のルール5）" "${token}")
        elseif("${rest}" MATCHES "^\\\\")
            set(token "${CMAKE_MATCH_0}")
            add_violation("${rel}:${line}" "\\ を書かない（行の連結を含む。ADR 0002 のルール5）" "")
        elseif("${rest}" MATCHES "^[A-Za-z_][A-Za-z0-9_]*")
            set(token "${CMAKE_MATCH_0}")
            if(token MATCHES "^[A-Z0-9_]*[A-Z][A-Z0-9_]*$" AND NOT token IN_LIST ALLOWED_UPPER_NAMES)
                add_violation("${rel}:${line}" "認めていない大文字の名前（PI、DEG2RAD、RAD2DEG だけ。ADR 0002 のルール5）" "${token}")
            endif()
        elseif("${rest}" MATCHES "${NUMBER_REGEX}")
            set(token "${CMAKE_MATCH_0}")
            is_allowed_number("${token}" allowed)
            if(NOT allowed)
                add_violation("${rel}:${line}" "認めていない数値（値が 0、1、2、0.5 の10進数だけ。ADR 0002 のルール5）" "${token}")
            endif()
        elseif("${rest}" MATCHES "^[^ \t\r\n/\"'\\\\A-Za-z0-9_.]+")
            set(token "${CMAKE_MATCH_0}")
        else()
            # 数値でない . と、コメントでない /
            string(SUBSTRING "${rest}" 0 1 token)
        endif()
        string(REGEX REPLACE "[^\n]" "" newlines "${token}")
        string(LENGTH "${newlines}" newline_count)
        math(EXPR line "${line} + ${newline_count}")
        string(LENGTH "${token}" token_len)
        string(SUBSTRING "${rest}" ${token_len} -1 rest)
    endwhile()
endfunction()

# 範囲を覚える。同じ敵 ID の範囲がもうあれば違反にする（中身の検査は呼び出し側で済ませておく）
function(register_range id rel begin_line text)
    get_property(known GLOBAL PROPERTY QP_RANGE_${id}_WHERE SET)
    if(known)
        get_property(first_where GLOBAL PROPERTY QP_RANGE_${id}_WHERE)
        add_violation("${rel}:${begin_line}" "同じ敵 ID の範囲がほかにもある（${first_where}。ADR 0002 のルール1）" "${id}")
        return()
    endif()
    # 空白・タブ・改行が続くところを空白1つにし、最初と最後の空白を取り除く（ADR 0002 のルール3）
    string(REGEX REPLACE "[ \t\r\n]+" " " code "${text}")
    string(REGEX REPLACE "^ " "" code "${code}")
    string(REGEX REPLACE " $" "" code "${code}")
    if(code STREQUAL "")
        add_violation("${rel}:${begin_line}" "QUINE 範囲が空" "${id}")
    endif()
    set_property(GLOBAL PROPERTY QP_RANGE_${id}_WHERE "${rel}:${begin_line}")
    set_property(GLOBAL PROPERTY QP_RANGE_${id}_CODE "${code}")
    set_property(GLOBAL APPEND PROPERTY QP_RANGE_IDS ${id})
endfunction()

# ---- 1. ソースから QUINE 範囲を切り出す ----

set_property(GLOBAL PROPERTY QP_RANGE_IDS "")
set_property(GLOBAL PROPERTY QP_NAMED_IDS "")
file(GLOB_RECURSE enemy_files LIST_DIRECTORIES false "${ENEMY_DIR}/*.h" "${ENEMY_DIR}/*.cpp")
list(SORT enemy_files)

foreach(path IN LISTS enemy_files)
    file(RELATIVE_PATH rel "${BASE_DIR}" "${path}")
    read_checked_file("${path}" "${rel}" rest read_ok)
    if(NOT read_ok)
        continue()
    endif()
    set(line_no 0)
    set(in_range FALSE)
    set(range_id "")
    set(range_begin 0)
    set(range_text "")
    while(NOT "${rest}" STREQUAL "")
        string(FIND "${rest}" "\n" newline)
        if(newline EQUAL -1)
            set(line "${rest}")
            set(rest "")
        else()
            string(SUBSTRING "${rest}" 0 ${newline} line)
            math(EXPR next "${newline} + 1")
            string(SUBSTRING "${rest}" ${next} -1 rest)
        endif()
        math(EXPR line_no "${line_no} + 1")
        string(REGEX REPLACE "\r$" "" line "${line}")

        if("${line}" MATCHES "${MARKER_REGEX}")
            set(marker "${CMAKE_MATCH_1}")
            string(REGEX REPLACE "^[ \t]*//[ \t]*QUINE-${marker}" "" after "${line}")
            string(STRIP "${after}" after)
            if(marker STREQUAL "BEGIN")
                # QUINE-BEGIN に書いた ID（余分な語があれば最初の語）を覚える。範囲を登録できなかった敵のマスクに、
                # 原因と合わない「対応する QUINE 範囲がない」を出さないため
                string(REGEX MATCH "^[^ \t]+" named_id "${after}")
                if(NOT named_id STREQUAL "")
                    set_property(GLOBAL APPEND PROPERTY QP_NAMED_IDS "${named_id}")
                endif()
                if(in_range)
                    add_violation("${rel}:${line_no}" "QUINE-BEGIN が入れ子になっている（${range_begin} 行目の範囲が閉じていない）" "${after}")
                    continue()
                endif()
                set(in_range TRUE)
                set(range_id "")
                set(range_begin ${line_no})
                set(range_text "")
                if(after STREQUAL "")
                    add_violation("${rel}:${line_no}" "QUINE-BEGIN のあとに敵 ID がない" "")
                elseif(after MATCHES "[ \t]")
                    add_violation("${rel}:${line_no}" "敵 ID のあとに余分な語がある" "${after}")
                elseif(NOT after MATCHES "${ID_REGEX}")
                    add_violation("${rel}:${line_no}" "敵 ID に使えない文字がある（英小文字・数字・_ だけ。ADR 0002 のルール1）" "${after}")
                else()
                    set(range_id "${after}")
                endif()
            else()
                if(NOT after STREQUAL "")
                    add_violation("${rel}:${line_no}" "QUINE-END のあとに余分な語がある" "${after}")
                endif()
                if(NOT in_range)
                    add_violation("${rel}:${line_no}" "QUINE-BEGIN のない QUINE-END" "")
                else()
                    # 違反をまとめて出すため、ID が正しくない範囲や、同じ ID の2つ目の範囲の中身も検査する
                    math(EXPR first_line "${range_begin} + 1")
                    check_range_text("${rel}" ${first_line} "${range_text}")
                    if(NOT range_id STREQUAL "")
                        register_range("${range_id}" "${rel}" ${range_begin} "${range_text}")
                    endif()
                    set(in_range FALSE)
                endif()
            endif()
        elseif(in_range)
            string(HEX "${line}" line_hex)
            if(line_hex MATCHES "^(..)*[89a-f]")
                add_violation("${rel}:${line_no}" "ASCII 以外の文字がある（ADR 0002 のルール7）" "")
            endif()
            # タブ（09）のほかの制御文字。行末の CR は取り除いてあり、行の途中の CR（0d）は空白としてまとめる
            if(line_hex MATCHES "^(..)*(0[0-8bcef]|1.|7f)")
                add_violation("${rel}:${line_no}" "制御文字がある（タブ、CR、LF のほかは書かない。ADR 0002 のルール7）" "")
            endif()
            string(APPEND range_text "${line}\n")
        endif()
    endwhile()
    if(in_range)
        add_violation("${rel}:${range_begin}" "QUINE-END がない" "${range_id}")
        math(EXPR first_line "${range_begin} + 1")
        check_range_text("${rel}" ${first_line} "${range_text}")
    endif()
endforeach()

# ---- 2. マスクを読んで検査する ----

file(RELATIVE_PATH mask_rel_dir "${BASE_DIR}" "${MASK_DIR}")
file(GLOB mask_files LIST_DIRECTORIES false "${MASK_DIR}/*.txt")
list(SORT mask_files)
set(mask_ids "")

foreach(path IN LISTS mask_files)
    file(RELATIVE_PATH rel "${BASE_DIR}" "${path}")
    get_filename_component(id "${path}" NAME_WLE)
    list(APPEND mask_ids "${id}")
    read_checked_file("${path}" "${rel}" rest read_ok)
    if(NOT read_ok)
        continue()
    endif()
    set(row_no 0)
    set(columns -1)
    set(cells "")
    set(hash_count 0)
    while(NOT "${rest}" STREQUAL "")
        string(FIND "${rest}" "\n" newline)
        if(newline EQUAL -1)
            set(row "${rest}")
            set(rest "")
        else()
            string(SUBSTRING "${rest}" 0 ${newline} row)
            math(EXPR next "${newline} + 1")
            string(SUBSTRING "${rest}" ${next} -1 rest)
        endif()
        math(EXPR row_no "${row_no} + 1")
        # 行末の CR は無視する（ADR 0002 のルール2）
        string(REGEX REPLACE "\r$" "" row "${row}")
        string(LENGTH "${row}" row_len)
        if("${row}" MATCHES "[^#$.]")
            string(REGEX MATCH "^[#$.]*" valid_prefix "${row}")
            string(LENGTH "${valid_prefix}" column)
            string(SUBSTRING "${row}" ${column} 1 bad)
            math(EXPR column "${column} + 1")
            if(NOT bad MATCHES "^[!-~]$")
                set(bad "")
            endif()
            add_violation("${rel}:${row_no}:${column}" "マスクに使えない文字（#、$、. だけ。ADR 0002 のルール2）" "${bad}")
        endif()
        if(columns EQUAL -1)
            set(columns ${row_len})
        elseif(NOT row_len EQUAL columns)
            add_violation("${rel}:${row_no}" "行の長さが1行目と違う（${row_len} 文字。1行目は ${columns} 文字。ADR 0002 のルール2）" "")
        endif()
        string(REGEX REPLACE "[^#]" "" hashes "${row}")
        string(LENGTH "${hashes}" row_hashes)
        math(EXPR hash_count "${hash_count} + ${row_hashes}")
        string(APPEND cells "${row}")
    endwhile()
    if(columns EQUAL -1)
        set(columns 0)
    endif()
    if(hash_count EQUAL 0)
        add_violation("${rel}" "# が1つもない（ADR 0002 のルール2）" "")
    endif()
    if(id MATCHES "^boss_")
        set(kind "ボス")
        set(max_columns ${BOSS_MAX_COLUMNS})
        set(max_rows ${BOSS_MAX_ROWS})
    else()
        set(kind "雑魚")
        set(max_columns ${ZAKO_MAX_COLUMNS})
        set(max_rows ${ZAKO_MAX_ROWS})
    endif()
    if(columns GREATER max_columns OR row_no GREATER max_rows)
        add_violation("${rel}" "大きさの上限を超えている（${kind}は ${max_columns}列×${max_rows}行まで。ADR 0002 のルール6）" "${columns}列×${row_no}行")
    endif()
    set(mask_${id}_columns ${columns})
    set(mask_${id}_rows ${row_no})
    set(mask_${id}_hashes ${hash_count})
    set(mask_${id}_cells "${cells}")
endforeach()

# ---- 3. 範囲とマスクの対応を確かめる（ADR 0002 のルール1） ----

get_property(range_ids GLOBAL PROPERTY QP_RANGE_IDS)
list(SORT range_ids)
get_property(has_nul GLOBAL PROPERTY QP_HAS_NUL)
get_property(named_ids GLOBAL PROPERTY QP_NAMED_IDS)
if(NOT has_nul)
    foreach(id IN LISTS range_ids)
        if(NOT id IN_LIST mask_ids)
            get_property(where GLOBAL PROPERTY QP_RANGE_${id}_WHERE)
            add_violation("${where}" "マスクがない（${mask_rel_dir}/${id}.txt）" "${id}")
        endif()
    endforeach()
    foreach(id IN LISTS mask_ids)
        # QUINE-BEGIN に書いたが、範囲に問題があって登録しなかった敵は、その違反がもう出ているので除く
        if(NOT id IN_LIST range_ids AND NOT id IN_LIST named_ids)
            add_violation("${mask_rel_dir}/${id}.txt" "対応する QUINE 範囲がない（敵 ID ${id}）" "")
        endif()
    endforeach()
endif()

get_property(violation_count GLOBAL PROPERTY QP_VIOLATION_COUNT)
if(violation_count GREATER 0)
    get_property(violations GLOBAL PROPERTY QP_VIOLATIONS)
    message(FATAL_ERROR "quine_pack: ${violation_count} 件の違反\n${violations}")
endif()

# ---- 4. マスクの # に詰めて、生成する .cpp を組み立てる（ADR 0002 のルール3） ----

# C++ の文字列リテラルの中身にする（\ と " をエスケープする）
function(escape_cpp text out_var)
    string(REPLACE "\\" "\\\\" text "${text}")
    string(REPLACE "\"" "\\\"" text "${text}")
    set(${out_var} "${text}" PARENT_SCOPE)
endfunction()

# マスクのマスを左上から順に見て、# にコードの文字を詰める。コードが尽きたら、空白を1つ入れて先頭に戻る
function(fill_mask code cells out_var)
    string(LENGTH "${code}" code_len)
    string(LENGTH "${cells}" cell_count)
    set(filled "")
    set(next_char 0)
    set(cell_index 0)
    while(cell_index LESS cell_count)
        string(SUBSTRING "${cells}" ${cell_index} 1 cell)
        if(cell STREQUAL "#")
            if(next_char EQUAL code_len)
                string(APPEND filled " ")
                set(next_char 0)
            else()
                string(SUBSTRING "${code}" ${next_char} 1 c)
                string(APPEND filled "${c}")
                math(EXPR next_char "${next_char} + 1")
            endif()
        elseif(cell STREQUAL "$")
            string(APPEND filled "$")
        else()
            string(APPEND filled " ")
        endif()
        math(EXPR cell_index "${cell_index} + 1")
    endwhile()
    set(${out_var} "${filled}" PARENT_SCOPE)
endfunction()

# columns 文字ごとに1行の文字列リテラルにして並べる（最後の行のあとに suffix を付ける）
function(rows_as_literals text columns rows suffix out_var)
    set(literals "")
    set(row 0)
    while(row LESS rows)
        math(EXPR start "${row} * ${columns}")
        string(SUBSTRING "${text}" ${start} ${columns} row_text)
        escape_cpp("${row_text}" row_text)
        math(EXPR row "${row} + 1")
        if(row EQUAL rows)
            string(APPEND literals "        \"${row_text}\"${suffix}\n")
        else()
            string(APPEND literals "        \"${row_text}\"\n")
        endif()
    endwhile()
    set(${out_var} "${literals}" PARENT_SCOPE)
endfunction()

set(generated "// quine_pack が生成したファイル。手で直さない（tools/quine_pack/quine_pack.cmake、ADR 0002）\n")
string(APPEND generated "#include \"enemies/enemy_text.h\"\n\nnamespace stg {\n\n")
list(LENGTH range_ids enemy_count)
if(enemy_count EQUAL 0)
    string(APPEND generated "std::span<const EnemyText> all_enemy_texts() {\n    return {};\n}\n")
else()
    string(APPEND generated "namespace {\n\nconstexpr EnemyText ENEMY_TEXTS[] = {\n")
    foreach(id IN LISTS range_ids)
        get_property(code GLOBAL PROPERTY QP_RANGE_${id}_CODE)
        set(columns ${mask_${id}_columns})
        set(rows ${mask_${id}_rows})
        fill_mask("${code}" "${mask_${id}_cells}" text)
        rows_as_literals("${mask_${id}_cells}" ${columns} ${rows} "," mask_literals)
        rows_as_literals("${text}" ${columns} ${rows} "," text_literals)
        string(APPEND generated "    {\n        \"${id}\", ${columns}, ${rows},\n")
        string(APPEND generated "        // マスク\n${mask_literals}")
        string(APPEND generated "        // テキスト\n${text_literals}")
        string(APPEND generated "    },\n")

        string(LENGTH "${code}" code_len)
        set(hashes ${mask_${id}_hashes})
        if(code_len GREATER hashes)
            math(EXPR cut "${code_len} - ${hashes}")
            set(note "${cut} 文字を切り捨てた")
        elseif(code_len LESS hashes)
            set(note "繰り返して詰めた")
        else()
            set(note "ちょうど詰めた")
        endif()
        message(STATUS "quine_pack: ${id}（${columns}列×${rows}行、# ${hashes} マス、コード ${code_len} 文字。${note}）")
    endforeach()
    string(APPEND generated "};\n\n}  // namespace\n\n")
    string(APPEND generated "std::span<const EnemyText> all_enemy_texts() {\n    return ENEMY_TEXTS;\n}\n")
endif()
string(APPEND generated "\n}  // namespace stg\n")

get_filename_component(output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${output_dir}")
file(WRITE "${OUTPUT}" "${generated}")
message(STATUS "quine_pack: ${enemy_count} 体の敵を ${OUTPUT} に書いた")
